//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAndFavorite
    {
        public int Id_Favorite { get; set; }
        public Nullable<int> Id_Comic { get; set; }
        public Nullable<int> Id_User { get; set; }
    
        public virtual Comic Comic { get; set; }
        public virtual User User { get; set; }
    }
}
